<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rpg_meta" nsURI="rpg_meta" nsPrefix="rpg_meta">
  <eClassifiers xsi:type="ecore:EClass" name="CharacterClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="characterstatistic" lowerBound="1"
        upperBound="-1" eType="#//CharacterStatistic" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//CharacterClass" eOpposite="#//CharacterClass/parents"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parents" upperBound="-1"
        eType="#//CharacterClass" eOpposite="#//CharacterClass/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="branches" lowerBound="1"
        upperBound="-1" eType="#//BranchRootNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//CharacterClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="branches" lowerBound="1"
        upperBound="-1" eType="#//Branch"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CharacterStatistic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BranchRootNode" eSuperTypes="#//BranchNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="branchnodes" lowerBound="1"
        upperBound="-1" eType="#//BranchNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//BranchRootNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BranchTypes">
    <eLiterals name="TALENT"/>
    <eLiterals name="ABILITY" value="1"/>
    <eLiterals name="MIXED" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BranchNode">
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Role"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextNodes" upperBound="-1"
        eType="#//BranchNode" eOpposite="#//BranchNode/parentNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentNode" lowerBound="1"
        eType="#//BranchNode" eOpposite="#//BranchNode/nextNodes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tooltip" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nodeType" eType="#//NodeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activatedStatus" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="levelStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="levelMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="levelMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activation" lowerBound="1"
        eType="#//NodeActivation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Branch">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lore"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="branchType" eType="#//BranchTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootNodes" lowerBound="1"
        upperBound="-1" eType="#//BranchRootNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootNodes" lowerBound="1"
        upperBound="-1" eType="#//BranchNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeActivation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAuto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbilityType"/>
  <eClassifiers xsi:type="ecore:EEnum" name="NodeType">
    <eLiterals name="ROOT"/>
    <eLiterals name="STANDARD" value="1"/>
    <eLiterals name="STANDALONE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeActivationAuto" eSuperTypes="#//NodeActivation"/>
  <eClassifiers xsi:type="ecore:EClass" name="EClass1"/>
  <eClassifiers xsi:type="ecore:EClass" name="NodeActivationBuy" eSuperTypes="#//NodeActivation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="costs" lowerBound="1" upperBound="-1"
        eType="#//ActivationCost" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeActivationPropagate" eSuperTypes="#//NodeActivation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="followsActivationOf" lowerBound="1"
        eType="#//BranchNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivationCost">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consume" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" lowerBound="1"
        eType="#//CharacterStatistic"/>
  </eClassifiers>
</ecore:EPackage>
